### ISSUE TITLE
HU01 - Consultar catálogo de álbumes

### ISSUE THREAD

**Issue by brayanhenao** [Miso-Code/misw4203-moviles-2023#1]
Como usuario visitante quiero navegar el catálogo de los álbumes para escoger los que más me interesa.

**Criterios de Aceptación**

- [x]  La lista se encuentra ordenada alfabéticamente de forma descendente con respecto al título(name) del album
- [x]  La lista muestra el título del album, su portada y fecha de lanzamiento
- [x]  Al hacer click sobre el elemento de la lista se debe redirigir a la vista de detalle del album: #2 
- [x] Se debe usar la imagen predefinida, en caso de que no llegue un cover(la imagen que se muestra en el mock)

**Comment by ocralo** [comment]
![Image](https://user-images.githubusercontent.com/25392457/229316463-f28115b7-e4ee-4a71-941e-2f488982f979.png)
