### ISSUE TITLE
HU02 - Consultar la información detallada de un álbum

### ISSUE THREAD

**Issue by brayanhenao** [Miso-Code/misw4203-moviles-2023#2]
Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él

**Criterios de Aceptación**

- [x]  Se muestra el título, portada, la fecha de lanzamiento, su descripción, género y nombre de la discográfica, así como la lista de sus tracks
- [x]  La lista de los tracks deberá ser ordenada según su posición dentro del álbum y deberá mostrar el nombre del track para cada elemento de la lista, así como su duración
- [x] En caso de que no llegue el cover, se debe usar la imagen por defecto que se muestra en el mock
- [x] En caso de no existir tracks, no se muestra dicha sección

**Comment by ocralo** [comment]
![Image](https://user-images.githubusercontent.com/25392457/229316471-fda6b911-5153-4a19-90b1-657d5f55860c.png)
