### ISSUE TITLE
HU03 - Consultar el listado de artistas

### ISSUE THREAD

**Issue by brayanhenao** [Miso-Code/misw4203-moviles-2023#3]
Como usuario visitante quiero ver el listado de artistas para escoger los que más me interesan

**Criterios de Aceptación**

- [x]  Se muestra el listado de artistas ordenado alfabéticamente en forma descendente con respecto al nombre del artista
- [x]  Al hacer click sobre el elemento de la lista deberá redirigirse a #4

**Comment by ocralo** [comment]
![Image](https://user-images.githubusercontent.com/25392457/229316478-57159476-db93-459a-90eb-de5c5833d8e3.png)
