### ISSUE TITLE
HU04 - Consultar la información detallada de un artista

### ISSUE THREAD

**Issue by brayanhenao** [Miso-Code/misw4203-moviles-2023#4]
Como usuario visitante quiero ver el detalle de un artista para ampliar la información sobre él

**Criterios de Aceptación**

- [x]  Le muestra el nombre completo del artista, la imagen, su descripción, y la lista de álbumes del artista
- [x]  La información de lista de álbumes deberá ser la misma que en #1 , pero sólo deberán aparecer los álbumes en los cuales participa el artista
- [x]  Al hacer click sobre el elemento de la lista de álbumes se debe redirigir a la vista de detalle del album: #2

**Comment by ocralo** [comment]
![Image](https://user-images.githubusercontent.com/25392457/229316483-fe4efe23-4fdd-4f21-9ade-20cfe6c0df0f.png)
