### ISSUE TITLE
HU05 - Consultar listado de coleccionistas

### ISSUE THREAD

**Issue by brayanhenao** [Miso-Code/misw4203-moviles-2023#5]
Como usuario visitante quiero consultar el listado de coleccionistas para seleccionar el que más me interesa

**Criterios de Aceptación**

- [x]  Se muestra el listado ordenado alfabéticamente  de forma descendente con respecto al nombre del coleccionista
- [x]  Al hacer click sobre el elemento de la lista se debe redirigir a la vista de detalle  del coleccionista: #6

**Comment by ocralo** [comment]
![Image](https://user-images.githubusercontent.com/25392457/229319523-54b88c3d-bbee-4620-add8-7b46abbfec85.png)
