### ISSUE TITLE
HU07 - Crear álbum

### ISSUE THREAD

**Issue by brayanhenao** [Miso-Code/misw4203-moviles-2023#7]
Como coleccionista, quiero crear un álbum en el listado de mi colección, para poder mantener un registro de los álbumes que tengo en mi colección. Del álbum quiero poder registrar su portada, nombre, la fecha de lanzamiento, la descripción, el género y la discográfica.

**Criterios de Aceptación**

- [ ] Todos los campos antes mencionados son de tipo string y son requeridos.
- [ ] El valor del campo género deberá ser uno de estos: **Classical, Salsa, Rock, Folk**
- [ ] El valor del campo discográfica deberá ser uno de estos: **Sony Music, EMI, Discos Fuentes, Elektra, Fania Records**
- [ ] El album creado debe aparecer en el catálogo: #1

**Comment by ocralo** [comment]
![Image](https://user-images.githubusercontent.com/25392457/229381300-9f3133df-5635-449a-8c35-31658daf4caf.png)
