### ISSUE TITLE
HU08 - Asociar tracks con un álbum

### ISSUE THREAD

**Issue by brayanhenao** [Miso-Code/misw4203-moviles-2023#8]
Como coleccionista quiero agregar tracks a un álbum para actualizar el catálogo. De los tracks deseo conocer su nombre y duración.

**Criterios de Aceptación**

- [ ] Todos los campos antes mencionados del track son de tipo string y son requeridos.
- [ ] El id del álbum al cual se asociará el track deberá existir.
- [ ] El track asociado deberá aparecer en: #2

**Comment by ocralo** [comment]
![Image](https://user-images.githubusercontent.com/25392457/229383187-4e76e647-3fd4-422d-9ee3-6b627e157429.png)
